### ISSUE TITLE
Document function and use of all commands

### ISSUE THREAD

**Issue by fulltrucker** [ginkgostreet/grav-util#4]
This module has the following commands, and I see that they're listed in the README file, but not all of them seem to do what the README file indicates they'll do? And I'm just not sure when to use what command to do what... and it seems like some commands use other commands in their processes?

`create`
`dev-env`
`docs-user`
`ginkgo-grav`
`grav-install`
`help`
`project-lab`
`project-lab-repo`

**Comment by fulltrucker** [comment]
Please see the link below for a narrative of my failed attempt at spinning up a Project Lab for IM4US:

https://github.com/ginkgostreet/ginkgo-docs-grav/blob/fulltrucker/pages/01.guides/01.project-setup/docs.md

I feel that concise, accurate documentation of what all the commands do, and how they should be used (or what they are to be used for) is needed here.

**Comment by caracolmzd** [comment]
I hope to make this issue moot soon, by refactoring the utils, likely into separate commands, especially for working on the server vs the offline workflow and cli cms.

Project Set-up guide has been updated regardless to clarify the key commands. 
https://docs.ginkgo.st/~docs/grav/guides/project-setup
